/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import proyecto_carlos_lara.ABBHistorial;
import proyecto_carlos_lara.Habitacion;
import proyecto_carlos_lara.HashTable;
import proyecto_carlos_lara.ABBReservaciones;

public class VentanaPrincipal extends javax.swing.JFrame {
    static ABBReservaciones a;
    static HashTable b;
    static ABBHistorial c;
    static Habitacion[] d;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(ABBReservaciones q, HashTable w, ABBHistorial e, Habitacion[] r) {
        this.a = q;
        this.b = w;
        this.c = e;
        this.d = r;
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bHistorial = new javax.swing.JButton();
        bHuespedes = new javax.swing.JButton();
        bReservaciones = new javax.swing.JButton();
        bChekin = new javax.swing.JButton();
        bCheckout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bHistorial.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        bHistorial.setForeground(new java.awt.Color(0, 153, 153));
        bHistorial.setText("Historial de Habitaciones");
        bHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHistorialActionPerformed(evt);
            }
        });
        jPanel1.add(bHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        bHuespedes.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        bHuespedes.setForeground(new java.awt.Color(0, 153, 153));
        bHuespedes.setText("Huespedes");
        bHuespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHuespedesActionPerformed(evt);
            }
        });
        jPanel1.add(bHuespedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, -1, -1));

        bReservaciones.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        bReservaciones.setForeground(new java.awt.Color(0, 153, 153));
        bReservaciones.setText("Ver Reservaciones");
        bReservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bReservacionesActionPerformed(evt);
            }
        });
        jPanel1.add(bReservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        bChekin.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        bChekin.setForeground(new java.awt.Color(0, 153, 153));
        bChekin.setText("Check-In");
        bChekin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChekinActionPerformed(evt);
            }
        });
        jPanel1.add(bChekin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        bCheckout.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        bCheckout.setForeground(new java.awt.Color(0, 153, 153));
        bCheckout.setText("Check-Out");
        bCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCheckoutActionPerformed(evt);
            }
        });
        jPanel1.add(bCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menu Hotel");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHistorialActionPerformed
        // TODO add your handling code here:
        VentanaHistorico vh = new VentanaHistorico(c);
    }//GEN-LAST:event_bHistorialActionPerformed

    private void bHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHuespedesActionPerformed
        // TODO add your handling code here:
        VentanaHuespedes vhu = new VentanaHuespedes(b,d);
    }//GEN-LAST:event_bHuespedesActionPerformed

    private void bReservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bReservacionesActionPerformed
        // TODO add your handling code here:
        VentanaReservas vr = new VentanaReservas(a);
    }//GEN-LAST:event_bReservacionesActionPerformed

    private void bChekinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChekinActionPerformed
        // TODO add your handling code here:
        VentanaCheckIn vci = new VentanaCheckIn(a,b,d);
    }//GEN-LAST:event_bChekinActionPerformed

    private void bCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCheckoutActionPerformed
        // TODO add your handling code here:
        VentanaCheckOut vco = new VentanaCheckOut(a,b,d,c);

    }//GEN-LAST:event_bCheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal( a,b,c,d).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCheckout;
    private javax.swing.JButton bChekin;
    private javax.swing.JButton bHistorial;
    private javax.swing.JButton bHuespedes;
    private javax.swing.JButton bReservaciones;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
